version: "3.3"

services:
    api:
      build: 
        context: ./api
        dockerfile: ./Dockerfile
      environment:
        DB_HOST: "db"
      depends_on: 
        - "db"
      ports:
        - 3000:3000
    pgadmin:
      image: "dpage/pgadmin4:latest"
      # env_file:
      environment: 
        PGADMIN_DEFAULT_EMAIL: admin@email.com
        PGADMIN_DEFAULT_PASSWORD: admin@email.com
      depends_on: 
        - "db"
      ports: 
        - 5050:80
      volumes:
        - pgadmin-data:/var/lib/pgadmin
        - ./pgadmin/servers.json:/pgadmin4/servers.json
    db:
      image: postgres:latest
      env_file:
        - ./db/.env
      ports: 
        - 5432:5432
      expose:
        - 5432
      volumes:
        - db-data:/var/lib/postgres/data
volumes:
  pgadmin-data:
  db-data:
          