services:
  db: 
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/d/var/lib/postgresql/data
      - ./db/scipts/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
