package mastercard

import "aggregator/merchants"

var SanitizerFns = []merchants.SanitizerFn{
	merchants.CreateSanitizer(`Amazon`, merchants.Amazon),
	merchants.CreateSanitizer(`AMZN`, merchants.Amazon),
	merchants.CreateSanitizer(`costco gas`, merchants.CostcoGas),
	merchants.CreateSanitizer(`google`, merchants.Google),
	merchants.CreateSanitizer(`wingsup!?`, merchants.WingsUp),
	merchants.CreateSanitizer(`Mongolian Grill`, merchants.MongolianGrill),
	merchants.CreateSanitizer(`PROPER BARBERSHOP`, merchants.ProperBarbershop),
	merchants.CreateSanitizer(`Mcdonald`, merchants.McDonalds),
	merchants.CreateSanitizer(`GARMIN`, merchants.Garmin),
	merchants.CreateSanitizer(`WAL-?MART`, merchants.Walmart),
	merchants.CreateSanitizer(`Youtube Music`, merchants.YoutubeMusic),
	merchants.CreateSanitizer(`PET`, merchants.PetValu),
	merchants.CreateSanitizer(`ANIMAL HOSPITAL OF CAM`, merchants.AnimalHospital),
	merchants.CreateSanitizer(`Petro`, merchants.PetroCanada),
	merchants.CreateSanitizer(`CERTAS HOME AUTO`, merchants.HomeInsurance),
	merchants.CreateSanitizer(`RCSS #\d+`, merchants.Superstore),
	merchants.CreateSanitizer(`Disney`, merchants.Disney),
	merchants.CreateSanitizer(`Waterloo catholic dist`, merchants.KidsSchool),
	merchants.CreateSanitizer(`ESSO`, merchants.Esso),
	merchants.CreateSanitizer(`Netflix`, merchants.Netflix),
	merchants.CreateSanitizer(`Costco wholesale`, merchants.Costco),
	merchants.CreateSanitizer(`TSI INTERNET`, merchants.TekSavvy),
	merchants.CreateSanitizer(`NAME-CHEAP`, merchants.DomainName),
	merchants.CreateSanitizer(`Parking`, merchants.Parking),
	merchants.CreateSanitizer(`PITA FACTORY`, merchants.PitaFactory),
	merchants.CreateSanitizer(`GREAT WOLF`, merchants.GreatWolfLodge),
	merchants.CreateSanitizer(`Busan`, merchants.BusanBBQ),
	merchants.CreateSanitizer(`ASHRAF DENTISTRY`, merchants.Dentist),
	merchants.CreateSanitizer(`Freedom Mobile`, merchants.Phones),
	merchants.CreateSanitizer(`GEMINI MOTORS`, merchants.CarMaintenance),
	merchants.CreateSanitizer(`GOG sp.`, merchants.Gog),
	merchants.CreateSanitizer(`ANGEL'S ON WESTMOUNT`, merchants.Angels),
	merchants.CreateSanitizer(`CREMA PASTRY`, merchants.Pastries),
	merchants.CreateSanitizer(`Bitwarden`, merchants.Bitwarden),
	merchants.CreateSanitizer(`Microsoft\*Store`, merchants.MicrosoftStore),
	merchants.CreateSanitizer(`SQ \*ISH AND CHIPS`, merchants.IshAndChips),
	merchants.CreateSanitizer(`Benjamin Tree Farm`, merchants.BenjaminTreeFarm),
	merchants.CreateSanitizer(`EXHALE`, merchants.MentalHealth),
	merchants.CreateSanitizer(`UBER CANADA/UBEREATS`, merchants.UberEats),
	merchants.CreateSanitizer(`FOOD BASICS`, merchants.FoodBasics),
	merchants.CreateSanitizer(`SHOPPERS DRUG MART`, merchants.ShoppersDrugMart),
	merchants.CreateSanitizer(`\*LA LOLA CATERING`, merchants.LaLola),
	merchants.CreateSanitizer(`STEAM PURCHASE`, merchants.Steam),
	merchants.CreateSanitizer(`PURCHASE INTEREST CHARGE`, merchants.Interest),
	merchants.CreateSanitizer(`PC EXPRESS`, merchants.GroceryDelivery),
	merchants.CreateSanitizer(`ABELL PEST CONTROL`, merchants.PestControl),
	merchants.CreateSanitizer(`STEAMGAMES\.COM`, merchants.Steam),
	merchants.CreateSanitizer(`GLOGOWSKI EURO FOOD`, merchants.Eurofood),
	merchants.CreateSanitizer(`Starbucks`, merchants.Starbucks),
	merchants.CreateSanitizer(`WATAMI`, merchants.Watami),
	merchants.CreateSanitizer(`PIONEER \d+`, merchants.PioneerGas),
	merchants.CreateSanitizer(`PIONEER STN`, merchants.PioneerGas),
	merchants.CreateSanitizer(`Home depot`, merchants.HomeDepot),
	merchants.CreateSanitizer(`RONA`, merchants.Rona),
	merchants.CreateSanitizer(`UBER\* EATS`, merchants.UberEats),
	merchants.CreateSanitizer(`UBERTRIP`, merchants.Uber),
	merchants.CreateSanitizer(`UBER\* TRIP`, merchants.Uber),
	merchants.CreateSanitizer(`DOMINOS`, merchants.Dominos),
	merchants.CreateSanitizer(`M&M Food`, merchants.MandMGroceries),
	merchants.CreateSanitizer(`MONTANAS COOKHOUSE`, merchants.Montanas),
	merchants.CreateSanitizer(`ACT\*KITCHENER`, merchants.ActKitchener),
	merchants.CreateSanitizer(`Grammarly`, merchants.Grammarly),
	merchants.CreateSanitizer(`YELLOWBAG`, merchants.Gardening),
	merchants.CreateSanitizer(`JOHNNY FRESCO`, merchants.JohnnyFresco),
	merchants.CreateSanitizer(`GINO'S PIZZA`, merchants.GinosPizza),
	merchants.CreateSanitizer(`Great Clips`, merchants.GreatClips),
	merchants.CreateSanitizer(`GOG\.com`, merchants.Gog),
	merchants.CreateSanitizer(`Covenant Cafe`, merchants.CovenantCafe),
	merchants.CreateSanitizer(`BELAIRDIRECT`, merchants.CarInsurance),
	merchants.CreateSanitizer(`Sansotei Ramen`, merchants.SansoteiRamen),
	merchants.CreateSanitizer(`MEADOW ACRES GARDEN`, merchants.Gardening),
	merchants.CreateSanitizer(`CALIBRE LLP`, merchants.Accountant),
	merchants.CreateSanitizer(`Canadian tire gas bar`, merchants.CanadianTireGas),
	merchants.CreateSanitizer(`canadian tire`, merchants.CanadianTire),
	merchants.CreateSanitizer(`UBIQUITI`, merchants.Ubuiquiti),
	merchants.CreateSanitizer(`KITCHENER WATERLOO HUM`, merchants.HumanSociety),
	merchants.CreateSanitizer(`THE JMBG NETWORK`, merchants.EthernetInstallation),
	merchants.CreateSanitizer(`SHELL C`, merchants.Shell),
	merchants.CreateSanitizer(`T&T SUPERMARKET`, merchants.TndTMarket),
	merchants.CreateSanitizer(`JAGEX`, merchants.Jagex),
	merchants.CreateSanitizer(`Morty's Pub`, merchants.Mortys),
	merchants.CreateSanitizer(`State & main`, merchants.StateAndMain),
	merchants.CreateSanitizer(`Grand River Hospital`, merchants.Hospital),
	merchants.CreateSanitizer(`Giant tiger`, merchants.GiantTiger),
	merchants.CreateSanitizer(`\*Arabella park`, merchants.ArabellaPark),
	merchants.CreateSanitizer(`\*PAZZO CO`, merchants.Pazzo),
	merchants.CreateSanitizer(`LAZEEZ SHAWARMA`, merchants.Lazees),
	merchants.CreateSanitizer(`ZEHRS`, merchants.Zehrs),
	merchants.CreateSanitizer(`ROCKY MOUNTAIN CHOCOLA`, merchants.Pastries),
	merchants.CreateSanitizer(`Paul & Mallory's`, merchants.NoFrils),
	merchants.CreateSanitizer(`UBER CANADA`, merchants.Uber),
	merchants.CreateSanitizer(`LANDMARK`, merchants.Landmark),
	merchants.CreateSanitizer(`LM Waterloo`, merchants.Landmark),
	merchants.CreateSanitizer(`DRIFTWOOD FAMILY EYECA`, merchants.EyeDoctor),
	merchants.CreateSanitizer(`QDOBA MEXICAN EATS`, merchants.Qdoba),
	merchants.CreateSanitizer(`CRATE AND BARREL`, merchants.CrateAndBarel),
	merchants.CreateSanitizer(`D SPOT DESSERT CAFFE`, merchants.DSpotDessertCaffe),
	merchants.CreateSanitizer(`A & W`, merchants.AAndW),
	merchants.CreateSanitizer(`THE FISH HUT`, merchants.TheFishHut),
	merchants.CreateSanitizer(`JINZAKAYA`, merchants.Jinzakaya),
	merchants.CreateSanitizer(`REG WATERLOO LANDFILL`, merchants.WasteDisposal),
	merchants.CreateSanitizer(`BINGEMANS CAMPING`, merchants.BingmenasCamping),
	merchants.CreateSanitizer(`Bingemans`, merchants.Bingmenas),
	merchants.CreateSanitizer(`BASKIN ROBBINS`, merchants.IceCream),
	merchants.CreateSanitizer(`Sobeys`, merchants.Sobeys),
	merchants.CreateSanitizer(`\*BLIZZARD US`, merchants.Blizzard),
	merchants.CreateSanitizer(`IKEA`, merchants.Ikea),
	merchants.CreateSanitizer(`SCOUTS CANADA`, merchants.Scouts),
	merchants.CreateSanitizer(`FUNVILLA`, merchants.FunVilla),
	merchants.CreateSanitizer(`SNUG HARBOUR`, merchants.SnugHarbour),
	merchants.CreateSanitizer(`DOLLARAMA`, merchants.Dollarama),
	merchants.CreateSanitizer(`Beertown`, merchants.Beertown),
	merchants.CreateSanitizer(`Lisboa Bakery`, merchants.Pastries),
	merchants.CreateSanitizer(`TELZE`, merchants.Phones),
	merchants.CreateSanitizer(`MR. PRETZELS`, merchants.MrPretzels),
	merchants.CreateSanitizer(`KRISPY KREME`, merchants.Pastries),
	merchants.CreateSanitizer(`INTEREST ADJUSTMENT`, merchants.InterestAdjustment),
	merchants.CreateSanitizer(`SP ROM COMMERCIAL`, merchants.Museum),
	merchants.CreateSanitizer("MILESTONES GRILL", merchants.MilestonesGrill),
	merchants.CreateSanitizer("ROBERTS BOXED MEATS", merchants.RobersBoxedMeats),
	merchants.CreateSanitizer("Golfs Steak", merchants.GoflsSTakeHouse),
	merchants.CreateSanitizer("RIEPERT SALT", merchants.RiepertSalt),
	merchants.CreateSanitizer("Electronic Deposit Payroll   Deposit Cognota Inc", merchants.Income),
}
