package mastercard

import "aggregator/merchants"

var sanitizerFns = []merchants.SanitizerFn{
	merchants.CreateSanitizer(`Amazon`, `Amazon`),
	merchants.CreateSanitizer(`AMZN`, `Amazon`),
	merchants.CreateSanitizer(`costgo gas`, `Gas`),
	merchants.CreateSanitizer(`google`, "Google"),
	merchants.CreateSanitizer(`wingsup!?`, "Take Out"),
	merchants.CreateSanitizer(`Mongolian Grill`, `Restaurant`),
	merchants.CreateSanitizer(`PROPER BARBERSHOP`, `Haircut`),
	merchants.CreateSanitizer(`Mcdonald`, `Restaurant`),
	merchants.CreateSanitizer(`GARMIN`, `Health`),
	merchants.CreateSanitizer(`WAL-?MART`, `Walmart`),
	merchants.CreateSanitizer(`Youtube Music`, `Music`),
	merchants.CreateSanitizer(`PET`, `Pet`),
	merchants.CreateSanitizer(`Animal`, `Vet`),
	merchants.CreateSanitizer(`Petro`, `Gas`),
	merchants.CreateSanitizer(`CERTAS HOME AUTO`, `Home Insurance`),
	merchants.CreateSanitizer(`RCSS #\d+`, `Superstore`),
	merchants.CreateSanitizer(`Disney`, `Disney`),
	merchants.CreateSanitizer(`Waterloo catholic dist`, `Kid's SChool`),
	merchants.CreateSanitizer(`ESSO`, `Gas`),
	merchants.CreateSanitizer(`Netflix`, `NetFlix`),
	merchants.CreateSanitizer(`Costco wholesale`, `Costco`),
	merchants.CreateSanitizer(`Costco gas`, `Gas`),
	merchants.CreateSanitizer(`TSI INTERNET`, `TekSavvy`),
	merchants.CreateSanitizer(`NAME-CHEAP`, `Domain name`),
	merchants.CreateSanitizer(`Parking`, `Parking`),
	merchants.CreateSanitizer(`PITA FACTORY`, `Restaurant`),
	merchants.CreateSanitizer(`GREAT WOLF`, `Great Wolf Lodge`),
	merchants.CreateSanitizer(`Busan`, `Restaurant`),
	merchants.CreateSanitizer(`ASHRAF DENTISTRY`, `Dentist`),
	merchants.CreateSanitizer(`Freedom Mobile`, `Phones`),
	merchants.CreateSanitizer(`GEMINI MOTORS`, `Car Maintenance`),
	merchants.CreateSanitizer(`GOG sp.`, `Video Games`),
	merchants.CreateSanitizer(`ANGEL'S ON WESTMOUNT`, "Restaurant"),
	merchants.CreateSanitizer(`CREMA PASTRY`, `Pastries`),
	merchants.CreateSanitizer(`Bitwarden`, `Bitwarden`),
	merchants.CreateSanitizer(`Microsoft\*Store`, `Video Games`),
	merchants.CreateSanitizer(`SQ \*ISH AND CHIPS`, `Restaurant`),
	merchants.CreateSanitizer(`Benjamin Tree Farm`, `Christmas Tree`),
	merchants.CreateSanitizer(`EXHALE`, `Mental Health`),
	merchants.CreateSanitizer(`UBER CANADA/UBEREATS`, `Take Out`),
	merchants.CreateSanitizer(`FOOD BASICS`, `Food Basics`),
	merchants.CreateSanitizer(`SHOPPERS DRUG MART`, `Shoppers Drug Mart`),
	merchants.CreateSanitizer(`\*LA LOLA CATERING`, `Restaurant`),
	merchants.CreateSanitizer(`STEAM PURCHASE`, `Video Games`),
	merchants.CreateSanitizer(`PURCHASE INTEREST CHARGE`, `Interest`),
	merchants.CreateSanitizer(`PC EXPRESS`, `Grocery Delivery`),
	merchants.CreateSanitizer(`ABELL PEST CONTROL`, `Pest Control`),
	merchants.CreateSanitizer(`STEAMGAMES\.COM`, `Video Games`),
	merchants.CreateSanitizer(`GLOGOWSKI EURO FOOD`, `Eurofood`),
	merchants.CreateSanitizer(`Starbucks`, `Starbucks`),
	merchants.CreateSanitizer(`WATAMI`, `Restaurants`),
	merchants.CreateSanitizer(`PIONEER \d+`, `Gas`),
	merchants.CreateSanitizer(`PIONEER STN`, `Gas`),
	merchants.CreateSanitizer(`Home depo`, `Home Improvement`),
	merchants.CreateSanitizer(`RONA`, `Home Improvement`),
	merchants.CreateSanitizer(`UBER\* EATS`, `Take Out`),
	merchants.CreateSanitizer(`UBERTRIP`, `Uber`),
	merchants.CreateSanitizer(`UBER\* TRIP`, `Uber`),
	merchants.CreateSanitizer(`DOMINOS`, `Take Out`),
	merchants.CreateSanitizer(`M&M Food`, `M&M (Groceries)`),
	merchants.CreateSanitizer(`MONTANAS COOKHOUSE`, `Restaurant`),
	merchants.CreateSanitizer(`ACT\*KITCHENER`, `Kids Activities`),
	merchants.CreateSanitizer(`Grammarly`, `Grammarly`),
	merchants.CreateSanitizer(`YELLOWBAG`, `Gardening`),
	merchants.CreateSanitizer(`JOHNNY FRESCO`, `Take Out`),
	merchants.CreateSanitizer(`GINO'S PIZZA`, `Take Out`),
	merchants.CreateSanitizer(`Great Clips`, `Haircut`),
	merchants.CreateSanitizer(`GOG.com`, `Video Games`),
	merchants.CreateSanitizer(`Covenant Cafe`, `Restaurant`),
	merchants.CreateSanitizer(`BELAIRDIRECT`, "Car Insurance"),
	merchants.CreateSanitizer(`Sansotei Ramen`, `Restaurant`),
	merchants.CreateSanitizer(`MEADOW ACRES GARDEN`, `Gardening`),
	merchants.CreateSanitizer(`CALIBRE LLP`, `Accountant`),
	merchants.CreateSanitizer(`Canadian tire gas bar`, `Gas`),
	merchants.CreateSanitizer(`canadian tire`, `Home Improvement`),
	merchants.CreateSanitizer(`UBIQUITI`, `Networking Gear`),
	merchants.CreateSanitizer(`KITCHENER WATERLOO HUM`, `Pets`),
	merchants.CreateSanitizer(`THE JMBG NETWORK`, `Ethernet Installation`),
	merchants.CreateSanitizer(`SHELL C`, `Gas`),
	merchants.CreateSanitizer(`T&T SUPERMARKET`, `Groceries`),
	merchants.CreateSanitizer(`JAGEX`, `Video Games`),
	merchants.CreateSanitizer(`Morty's Pub`, `Restaurant`),
	merchants.CreateSanitizer(`State & main`, `Restaurant`),
	merchants.CreateSanitizer(`Grand River Hospital`, `Hospital`),
	merchants.CreateSanitizer(`Giant tiger`, `Groceries`),
	merchants.CreateSanitizer(`\*Arabella park`, `Restaurant`),
	merchants.CreateSanitizer(`\*PAZZO CO`, `Restaurant`),
	merchants.CreateSanitizer(`LAZEEZ SHAWARMA`, `Restaurant`),
	merchants.CreateSanitizer(`ZEHRS`, `Groceries`),
	merchants.CreateSanitizer(`ROCKY MOUNTAIN CHOCOLA`, `Pastries`),
	merchants.CreateSanitizer(`Paul & Mallory's`, `Groceries`),
	merchants.CreateSanitizer(`UBER CANADA`, `Uber`),
	merchants.CreateSanitizer(`LANDMARK`, `Movie Theatre`),
	merchants.CreateSanitizer(`LM Waterloo`, `Movie Theatre`),
	merchants.CreateSanitizer(`DRIFTWOOD FAMILY EYECA`, `Eye Doctor`),
	merchants.CreateSanitizer(`QDOBA MEXICAN EATS`, `Restaurant`),
	merchants.CreateSanitizer(`CRATE AND BARREL`, `Restaurant`),
	merchants.CreateSanitizer(`D SPOT DESSERT CAFFE`, `Restaurant`),
	merchants.CreateSanitizer(`A & W`, `Restaurant`),
	merchants.CreateSanitizer(`THE FISH HUT`, `Take Out`),
	merchants.CreateSanitizer(`JINZAKAYA`, `Restaurant`),
	merchants.CreateSanitizer(`REG WATERLOO LANDFILL`, `Waste Disposal`),
	merchants.CreateSanitizer(`BINGEMANS CAMPING`, `Camping`),
	merchants.CreateSanitizer(`Bingemans`, `Kids Activities`),
	merchants.CreateSanitizer(`BASKIN ROBBINS`, `Ice Cream`),
	merchants.CreateSanitizer(`Sobeys`, `Groceries`),
	merchants.CreateSanitizer(`\*BLIZZARD US`, `Video Games`),
	merchants.CreateSanitizer(`IKEA`, `Furniture`),
	merchants.CreateSanitizer(`SCOUTS CANADA`, `Kid's Activities`),
	merchants.CreateSanitizer(`FUNVILLA`, `Kid's Activities`),
	merchants.CreateSanitizer(`SNUG HARBOUR`, `Restaurant`),
	merchants.CreateSanitizer(`DOLLARAMA`, `Misc`),
	merchants.CreateSanitizer(`Beertown`, `Restaurant`),
	merchants.CreateSanitizer(`Lisboa Bakery`, `Pastries`),
	merchants.CreateSanitizer(`TELZE`, `Phones`),
	merchants.CreateSanitizer(`MR. PRETZELS`, `Take Out`),
	merchants.CreateSanitizer(`KRISPY KREME`, `Pastries`),
	merchants.CreateSanitizer(`INTEREST ADJUSTMENT`, `Interest Adjustment`),
	merchants.CreateSanitizer(`SP ROM COMMERCIAL`, `Kids Activities`),
}
